Scriptname FullBodiedQuestScript  Hidden 

; FullBodiedAnimations official quest script with native C++ plugin interface
; This is the canonical script for FullBodied; the duplicate 'FullBodied.psc' was removed.

; Reloads configuration from INI files (FBConfig.cpp)
; Safe to call from any thread (uses atomic snapshot pattern)
; Returns: true if reload succeeded, false if INI parse error occurred
bool Function ReloadConfig() global native

; Drains pending animation events from the event queue (FBEvents.cpp)
; Called periodically from C++ plugin main tick loop
; Returns: number of events that were drained
; NOTE: Events are generated by Payload Interpreter "PIE" in animation graphs
;       Tags format: "FB:scriptKey" for animations, "FB_PAIR_END:scriptKey" for end markers
int Function DrainEvents() global native

; Manually trigger one frame of animation processing (FBUpdate.cpp)
; Normally called automatically every game frame, but exposed for debug/testing
; Returns: 1 if processed successfully, 0 otherwise
int Function TickOnce() global native